version: "3"

services:
  rasa:
    build: 
      context: .
      dockerfile: Dockerfile.rasa
      args:
        - RASA_VERSION=$RASA_VERSION
        - RASA_X_VERSION=$RASA_X_VERSION
        - PYTHON_VERSION=$PYTHON_VERSION
    container_name: rasa-cpu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  action-server:
    build: 
      context: .
      dockerfile: Dockerfile.actions
      args:
        - RASA_SDK_VERSION=$RASA_SDK_VERSION
    environment:
      - RASA_SDK_VERSION=$RASA_SDK_VERSION
    container_name: action-server
    volumes:
      - ./actions:/app/actions
    command:
      - start
    ports:
      - 5055:5055
    networks: ['rasa-network']

networks: {
  rasa-network: {}
}